server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-demo?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  jackson:
    default-property-inclusion: non_null

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

